# Generated by Django 4.0 on 2023-11-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_partner_email_alter_partner_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway_name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default=False, upload_to='')),
                ('description', models.TextField()),
                ('gateway_link', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
