# Generated by Django 4.0 on 2023-11-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_donationmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='amount',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='plegde',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
