# Generated by Django 4.0 on 2023-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
                ('about_the_prophet', models.TextField()),
                ('social_link_1', models.CharField(default='#', max_length=500)),
                ('social_link_2', models.CharField(default='#', max_length=500)),
                ('social_link_3', models.CharField(default='#', max_length=500)),
                ('social_link_4', models.CharField(default='#', max_length=500)),
                ('social_link_5', models.CharField(default='#', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='charity')),
                ('title', models.CharField(default='', max_length=50)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Church_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
                ('service_day', models.CharField(default='', max_length=50)),
                ('features', models.TextField()),
                ('serive_time', models.TimeField()),
            ],
        ),
    ]
