# Generated by Django 4.0 on 2023-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church_program',
            name='serive_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
