# Generated by Django 4.0 on 2023-11-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_church_program_serive_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church_program',
            old_name='serive_time',
            new_name='service_time',
        ),
    ]
