# Generated by Django 4.0 on 2023-11-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_rename_serive_time_church_program_service_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='social_link_1',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='social_link_2',
            new_name='instagram_link',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='social_link_3',
            new_name='twitter_link',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='social_link_4',
            new_name='whats_app_link',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='social_link_5',
            new_name='youtube_link',
        ),
    ]
