# Generated by Django 4.0 on 2023-11-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_rename_social_link_1_about_facebook_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Church_program',
            new_name='ChurchProgram',
        ),
    ]
